import type { RequirementProfile } from "@feedingsystem/contracts";

export const DEFAULT_REQUIREMENT_PROFILES: RequirementProfile[] = [
  {
    id: "req-growing-early",
    stage: "growing_early",
    min_weight_kg: 150,
    max_weight_kg: 300,
    min_adg: 0.7,
    max_adg: 1.0,
    target_cp_pct_dm: 15.5,
    target_tdn_pct_dm: 72,
    target_ndf_min_pct_dm: 28,
    target_ndf_max_pct_dm: 38,
    target_adf_min_pct_dm: 17,
    target_adf_max_pct_dm: 25,
    target_ca_pct_dm: 0.55,
    target_p_pct_dm: 0.32,
    version: "default-2026.1",
    is_current: true,
  },
  {
    id: "req-growing-late",
    stage: "growing_late",
    min_weight_kg: 300,
    max_weight_kg: 450,
    min_adg: 0.7,
    max_adg: 1.1,
    target_cp_pct_dm: 14,
    target_tdn_pct_dm: 71,
    target_ndf_min_pct_dm: 30,
    target_ndf_max_pct_dm: 40,
    target_adf_min_pct_dm: 18,
    target_adf_max_pct_dm: 27,
    target_ca_pct_dm: 0.5,
    target_p_pct_dm: 0.3,
    version: "default-2026.1",
    is_current: true,
  },
  {
    id: "req-fattening-early",
    stage: "fattening_early",
    min_weight_kg: 450,
    max_weight_kg: 550,
    min_adg: 0.8,
    max_adg: 1.2,
    target_cp_pct_dm: 13,
    target_tdn_pct_dm: 73,
    target_ndf_min_pct_dm: 28,
    target_ndf_max_pct_dm: 36,
    target_adf_min_pct_dm: 17,
    target_adf_max_pct_dm: 23,
    target_ca_pct_dm: 0.45,
    target_p_pct_dm: 0.28,
    version: "default-2026.1",
    is_current: true,
  },
  {
    id: "req-fattening-mid",
    stage: "fattening_mid",
    min_weight_kg: 550,
    max_weight_kg: 650,
    min_adg: 0.7,
    max_adg: 1.1,
    target_cp_pct_dm: 12,
    target_tdn_pct_dm: 74,
    target_ndf_min_pct_dm: 27,
    target_ndf_max_pct_dm: 34,
    target_adf_min_pct_dm: 16,
    target_adf_max_pct_dm: 22,
    target_ca_pct_dm: 0.42,
    target_p_pct_dm: 0.26,
    version: "default-2026.1",
    is_current: true,
  },
  {
    id: "req-fattening-late",
    stage: "fattening_late",
    min_weight_kg: 650,
    max_weight_kg: 900,
    min_adg: 0.6,
    max_adg: 1.0,
    target_cp_pct_dm: 11,
    target_tdn_pct_dm: 75,
    target_ndf_min_pct_dm: 26,
    target_ndf_max_pct_dm: 33,
    target_adf_min_pct_dm: 15,
    target_adf_max_pct_dm: 21,
    target_ca_pct_dm: 0.4,
    target_p_pct_dm: 0.24,
    version: "default-2026.1",
    is_current: true,
  },
  {
    id: "req-breeding",
    stage: "breeding",
    min_weight_kg: 450,
    max_weight_kg: 800,
    min_adg: 0.4,
    max_adg: 0.8,
    target_cp_pct_dm: 12.5,
    target_tdn_pct_dm: 68,
    target_ndf_min_pct_dm: 32,
    target_ndf_max_pct_dm: 42,
    target_adf_min_pct_dm: 20,
    target_adf_max_pct_dm: 29,
    target_ca_pct_dm: 0.55,
    target_p_pct_dm: 0.32,
    version: "default-2026.1",
    is_current: true,
  },
];
