import Foundation

enum IngredientSelectionGroup: String, Codable {
    case tmr
    case mineral
}

extension IngredientCategory {
    static func fromSourceCategory(_ category: String) -> IngredientCategory {
        switch category {
        case "곡류": return .concentrate
        case "강피류": return .concentrate
        case "유박류": return .concentrate
        case "견과종실류": return .concentrate
        case "농식품부산물": return .agriByproduct
        case "섬유질류_기타": return .agriByproduct
        case "목초": return .roughage
        case "고간류": return .roughage
        case "사일리지 및 청예조사료": return .roughage
        case "광물질": return .supplement
        default: return .agriByproduct
        }
    }
}

extension PrototypeStore {
    static let ingredientCatalog: [IngredientDefinition] = [
        IngredientDefinition(
            id: "CUSTOM_SOYBEAN_MEAL",
            sourceFeedNo: 10001,
            name: "대두박",
            sourceCategory: "유박류",
            selectionGroup: .tmr,
            category: .concentrate,
            defaultPriceKrwPerKg: 790,
            nutrition: IngredientNutritionProfile(
                moisturePct: 11.0,
                dmPct: 89.0,
                cpPctDm: 49.0,
                tdnPctDm: 84.0,
                ndfPctDm: 14.0,
                adfPctDm: 8.0,
                nfcPctDm: 29.1,
                eePctDm: 1.5,
                ashPctDm: 6.4,
                caPctDm: 0.35,
                pPctDm: 0.72
            )
        ),
        IngredientDefinition(
            id: "CUSTOM_YEAST_CULTURE",
            sourceFeedNo: 10002,
            name: "이스트컬쳐",
            sourceCategory: "보충사료",
            selectionGroup: .mineral,
            category: .supplement,
            defaultPriceKrwPerKg: 1200,
            nutrition: IngredientNutritionProfile(
                moisturePct: 5.0,
                dmPct: 95.0,
                cpPctDm: 0.0,
                tdnPctDm: 0.0,
                ndfPctDm: 0.0,
                adfPctDm: 0.0,
                nfcPctDm: 0.0,
                eePctDm: 0.0,
                ashPctDm: 0.0,
                caPctDm: 0.0,
                pPctDm: 0.0
            )
        ),
        IngredientDefinition(
            id: "FEED_1",
            sourceFeedNo: 1,
            name: "귀리(연맥)",
            sourceCategory: "곡류",
            selectionGroup: .tmr,
            category: .concentrate,
            defaultPriceKrwPerKg: 460,
            nutrition: IngredientNutritionProfile(
                moisturePct: 12.16,
                dmPct: 87.84,
                cpPctDm: 10.97,
                tdnPctDm: 74.83,
                ndfPctDm: 33.97,
                adfPctDm: 16.21,
                nfcPctDm: 47.69,
                eePctDm: 4.43,
                ashPctDm: 2.91,
                caPctDm: 0.07,
                pPctDm: 0.35
            )
        ),
        IngredientDefinition(
            id: "FEED_2",
            sourceFeedNo: 2,
            name: "밀(소맥)",
            sourceCategory: "곡류",
            selectionGroup: .tmr,
            category: .concentrate,
            defaultPriceKrwPerKg: 460,
            nutrition: IngredientNutritionProfile(
                moisturePct: 12.13,
                dmPct: 87.87,
                cpPctDm: 12.86,
                tdnPctDm: 88.48,
                ndfPctDm: 14.13,
                adfPctDm: 3.43,
                nfcPctDm: 69.57,
                eePctDm: 1.66,
                ashPctDm: 1.75,
                caPctDm: 0.05,
                pPctDm: 0.35
            )
        ),
        IngredientDefinition(
            id: "FEED_3",
            sourceFeedNo: 3,
            name: "보리(대맥)",
            sourceCategory: "곡류",
            selectionGroup: .tmr,
            category: .concentrate,
            defaultPriceKrwPerKg: 460,
            nutrition: IngredientNutritionProfile(
                moisturePct: 10.68,
                dmPct: 89.32,
                cpPctDm: 10.72,
                tdnPctDm: 85.0,
                ndfPctDm: 18.45,
                adfPctDm: 6.03,
                nfcPctDm: 66.4,
                eePctDm: 2.07,
                ashPctDm: 2.34,
                caPctDm: 0.05,
                pPctDm: 0.31
            )
        ),
        IngredientDefinition(
            id: "FEED_4",
            sourceFeedNo: 4,
            name: "파쇄옥수수",
            sourceCategory: "곡류",
            selectionGroup: .tmr,
            category: .concentrate,
            defaultPriceKrwPerKg: 460,
            nutrition: IngredientNutritionProfile(
                moisturePct: 14.12,
                dmPct: 85.88,
                cpPctDm: 8.42,
                tdnPctDm: 89.36,
                ndfPctDm: 9.72,
                adfPctDm: 2.48,
                nfcPctDm: 76.6,
                eePctDm: 3.92,
                ashPctDm: 1.32,
                caPctDm: 0.01,
                pPctDm: 0.26
            )
        ),
        IngredientDefinition(
            id: "FEED_7",
            sourceFeedNo: 7,
            name: "옥수수(후레이크)",
            sourceCategory: "곡류",
            selectionGroup: .tmr,
            category: .concentrate,
            defaultPriceKrwPerKg: 460,
            nutrition: IngredientNutritionProfile(
                moisturePct: 13.09,
                dmPct: 86.91,
                cpPctDm: 8.49,
                tdnPctDm: 93.8,
                ndfPctDm: 13.6,
                adfPctDm: 7.9,
                nfcPctDm: 72.6,
                eePctDm: 3.77,
                ashPctDm: 1.52,
                caPctDm: 0.01,
                pPctDm: 0.26
            )
        ),
        IngredientDefinition(
            id: "FEED_8",
            sourceFeedNo: 8,
            name: "현미(재고미)",
            sourceCategory: "곡류",
            selectionGroup: .tmr,
            category: .concentrate,
            defaultPriceKrwPerKg: 460,
            nutrition: IngredientNutritionProfile(
                moisturePct: 14.05,
                dmPct: 85.95,
                cpPctDm: 8.56,
                tdnPctDm: 89.54,
                ndfPctDm: 10.94,
                adfPctDm: 2.76,
                nfcPctDm: 76.15,
                eePctDm: 3.03,
                ashPctDm: 1.29,
                caPctDm: 0.02,
                pPctDm: 0.26
            )
        ),
        IngredientDefinition(
            id: "FEED_9",
            sourceFeedNo: 9,
            name: "호밀",
            sourceCategory: "곡류",
            selectionGroup: .tmr,
            category: .concentrate,
            defaultPriceKrwPerKg: 460,
            nutrition: IngredientNutritionProfile(
                moisturePct: 3.03,
                dmPct: 96.97,
                cpPctDm: 12.52,
                tdnPctDm: 83.12,
                ndfPctDm: 13.9,
                adfPctDm: 3.2,
                nfcPctDm: 69.31,
                eePctDm: 1.7,
                ashPctDm: 2.56,
                caPctDm: 0.04,
                pPctDm: 0.31
            )
        ),
        IngredientDefinition(
            id: "FEED_10",
            sourceFeedNo: 10,
            name: "귀리피",
            sourceCategory: "강피류",
            selectionGroup: .tmr,
            category: .agriByproduct,
            defaultPriceKrwPerKg: 410,
            nutrition: IngredientNutritionProfile(
                moisturePct: 8.8,
                dmPct: 91.2,
                cpPctDm: 5.43,
                tdnPctDm: 56.53,
                ndfPctDm: 66.13,
                adfPctDm: 32.86,
                nfcPctDm: 20.42,
                eePctDm: 2.52,
                ashPctDm: 5.47,
                caPctDm: 0.34,
                pPctDm: 0.12
            )
        ),
        IngredientDefinition(
            id: "FEED_11",
            sourceFeedNo: 11,
            name: "대두피",
            sourceCategory: "강피류",
            selectionGroup: .tmr,
            category: .concentrate,
            defaultPriceKrwPerKg: 410,
            nutrition: IngredientNutritionProfile(
                moisturePct: 10.27,
                dmPct: 89.73,
                cpPctDm: 13.35,
                tdnPctDm: 62.64,
                ndfPctDm: 59.9,
                adfPctDm: 42.98,
                nfcPctDm: 18.74,
                eePctDm: 3.15,
                ashPctDm: 4.83,
                caPctDm: 0.55,
                pPctDm: 0.18
            )
        ),
        IngredientDefinition(
            id: "FEED_12",
            sourceFeedNo: 12,
            name: "루핀피",
            sourceCategory: "강피류",
            selectionGroup: .tmr,
            category: .agriByproduct,
            defaultPriceKrwPerKg: 410,
            nutrition: IngredientNutritionProfile(
                moisturePct: 7.96,
                dmPct: 92.04,
                cpPctDm: 7.69,
                tdnPctDm: 75.26,
                ndfPctDm: 0.0,
                adfPctDm: 0.0,
                nfcPctDm: 18.74,
                eePctDm: 2.3,
                ashPctDm: 2.74,
                caPctDm: 0.0,
                pPctDm: 0.0
            )
        ),
        IngredientDefinition(
            id: "FEED_13",
            sourceFeedNo: 13,
            name: "면실피",
            sourceCategory: "강피류",
            selectionGroup: .tmr,
            category: .agriByproduct,
            defaultPriceKrwPerKg: 410,
            nutrition: IngredientNutritionProfile(
                moisturePct: 9.99,
                dmPct: 90.01,
                cpPctDm: 7.4,
                tdnPctDm: 48.03,
                ndfPctDm: 76.33,
                adfPctDm: 56.72,
                nfcPctDm: 8.91,
                eePctDm: 1.95,
                ashPctDm: 5.39,
                caPctDm: 0.55,
                pPctDm: 0.2
            )
        ),
        IngredientDefinition(
            id: "FEED_14",
            sourceFeedNo: 14,
            name: "보릿겨(맥강)",
            sourceCategory: "강피류",
            selectionGroup: .tmr,
            category: .concentrate,
            defaultPriceKrwPerKg: 410,
            nutrition: IngredientNutritionProfile(
                moisturePct: 8.49,
                dmPct: 91.51,
                cpPctDm: 13.56,
                tdnPctDm: 56.55,
                ndfPctDm: 49.15,
                adfPctDm: 21.06,
                nfcPctDm: 27.55,
                eePctDm: 1.96,
                ashPctDm: 7.76,
                caPctDm: 0.14,
                pPctDm: 0.36
            )
        ),
        IngredientDefinition(
            id: "FEED_15",
            sourceFeedNo: 15,
            name: "수수겨",
            sourceCategory: "강피류",
            selectionGroup: .tmr,
            category: .agriByproduct,
            defaultPriceKrwPerKg: 410,
            nutrition: IngredientNutritionProfile(
                moisturePct: 9.56,
                dmPct: 90.44,
                cpPctDm: 12.25,
                tdnPctDm: 69.97,
                ndfPctDm: 42.9,
                adfPctDm: 11.5,
                nfcPctDm: 5.0,
                eePctDm: 6.8,
                ashPctDm: 5.21,
                caPctDm: 0.0,
                pPctDm: 0.0
            )
        ),
        IngredientDefinition(
            id: "FEED_16",
            sourceFeedNo: 16,
            name: "쌀겨(생미강)",
            sourceCategory: "강피류",
            selectionGroup: .tmr,
            category: .concentrate,
            defaultPriceKrwPerKg: 410,
            nutrition: IngredientNutritionProfile(
                moisturePct: 11.68,
                dmPct: 88.32,
                cpPctDm: 15.88,
                tdnPctDm: 91.25,
                ndfPctDm: 23.1,
                adfPctDm: 9.22,
                nfcPctDm: 30.5,
                eePctDm: 20.64,
                ashPctDm: 9.85,
                caPctDm: 0.07,
                pPctDm: 2.17
            )
        ),
        IngredientDefinition(
            id: "FEED_17",
            sourceFeedNo: 17,
            name: "아몬드피",
            sourceCategory: "강피류",
            selectionGroup: .tmr,
            category: .agriByproduct,
            defaultPriceKrwPerKg: 410,
            nutrition: IngredientNutritionProfile(
                moisturePct: 10.31,
                dmPct: 89.69,
                cpPctDm: 4.0,
                tdnPctDm: 54.88,
                ndfPctDm: 70.46,
                adfPctDm: 49.98,
                nfcPctDm: 17.67,
                eePctDm: 1.62,
                ashPctDm: 6.23,
                caPctDm: 0.29,
                pPctDm: 0.06
            )
        ),
        IngredientDefinition(
            id: "FEED_18",
            sourceFeedNo: 18,
            name: "옥수수단백피",
            sourceCategory: "강피류",
            selectionGroup: .tmr,
            category: .agriByproduct,
            defaultPriceKrwPerKg: 410,
            nutrition: IngredientNutritionProfile(
                moisturePct: 8.21,
                dmPct: 91.79,
                cpPctDm: 22.22,
                tdnPctDm: 78.67,
                ndfPctDm: 38.18,
                adfPctDm: 10.45,
                nfcPctDm: 29.81,
                eePctDm: 2.96,
                ashPctDm: 6.81,
                caPctDm: 0.12,
                pPctDm: 0.82
            )
        ),
        IngredientDefinition(
            id: "FEED_19",
            sourceFeedNo: 19,
            name: "율무피",
            sourceCategory: "강피류",
            selectionGroup: .tmr,
            category: .agriByproduct,
            defaultPriceKrwPerKg: 410,
            nutrition: IngredientNutritionProfile(
                moisturePct: 5.08,
                dmPct: 94.92,
                cpPctDm: 2.72,
                tdnPctDm: 43.3,
                ndfPctDm: 70.63,
                adfPctDm: 54.98,
                nfcPctDm: 12.46,
                eePctDm: 1.83,
                ashPctDm: 12.33,
                caPctDm: 0.13,
                pPctDm: 0.13
            )
        ),
        IngredientDefinition(
            id: "FEED_20",
            sourceFeedNo: 20,
            name: "캐슈너트피",
            sourceCategory: "강피류",
            selectionGroup: .tmr,
            category: .agriByproduct,
            defaultPriceKrwPerKg: 410,
            nutrition: IngredientNutritionProfile(
                moisturePct: 9.65,
                dmPct: 90.35,
                cpPctDm: 12.7,
                tdnPctDm: 77.31,
                ndfPctDm: 31.93,
                adfPctDm: 24.6,
                nfcPctDm: 41.0,
                eePctDm: 12.28,
                ashPctDm: 2.06,
                caPctDm: 0.12,
                pPctDm: 0.14
            )
        ),
        IngredientDefinition(
            id: "FEED_22",
            sourceFeedNo: 22,
            name: "겨자박(압착)",
            sourceCategory: "유박류",
            selectionGroup: .tmr,
            category: .concentrate,
            defaultPriceKrwPerKg: 620,
            nutrition: IngredientNutritionProfile(
                moisturePct: 10.6,
                dmPct: 89.4,
                cpPctDm: 22.96,
                tdnPctDm: 0.0,
                ndfPctDm: 0.0,
                adfPctDm: 0.0,
                nfcPctDm: 0.0,
                eePctDm: 10.06,
                ashPctDm: 14.19,
                caPctDm: 0.51,
                pPctDm: 0.51
            )
        ),
        IngredientDefinition(
            id: "FEED_23",
            sourceFeedNo: 23,
            name: "구아박",
            sourceCategory: "유박류",
            selectionGroup: .tmr,
            category: .concentrate,
            defaultPriceKrwPerKg: 620,
            nutrition: IngredientNutritionProfile(
                moisturePct: 6.55,
                dmPct: 93.45,
                cpPctDm: 49.44,
                tdnPctDm: 78.37,
                ndfPctDm: 25.6,
                adfPctDm: 12.9,
                nfcPctDm: 13.61,
                eePctDm: 5.44,
                ashPctDm: 5.89,
                caPctDm: 0.7,
                pPctDm: 0.64
            )
        ),
        IngredientDefinition(
            id: "FEED_24",
            sourceFeedNo: 24,
            name: "대두단백(농축)",
            sourceCategory: "유박류",
            selectionGroup: .tmr,
            category: .concentrate,
            defaultPriceKrwPerKg: 620,
            nutrition: IngredientNutritionProfile(
                moisturePct: 7.12,
                dmPct: 92.88,
                cpPctDm: 65.19,
                tdnPctDm: 87.74,
                ndfPctDm: 5.6,
                adfPctDm: 2.0,
                nfcPctDm: 20.79,
                eePctDm: 3.8,
                ashPctDm: 4.6,
                caPctDm: 0.0,
                pPctDm: 0.41
            )
        ),
        IngredientDefinition(
            id: "FEED_25",
            sourceFeedNo: 25,
            name: "대두단백(분리)",
            sourceCategory: "유박류",
            selectionGroup: .tmr,
            category: .concentrate,
            defaultPriceKrwPerKg: 620,
            nutrition: IngredientNutritionProfile(
                moisturePct: 5.42,
                dmPct: 94.58,
                cpPctDm: 91.06,
                tdnPctDm: 89.94,
                ndfPctDm: 0.0,
                adfPctDm: 0.0,
                nfcPctDm: 0.0,
                eePctDm: 0.41,
                ashPctDm: 4.73,
                caPctDm: 0.24,
                pPctDm: 0.91
            )
        ),
        IngredientDefinition(
            id: "FEED_26",
            sourceFeedNo: 26,
            name: "들깻묵(임자박)",
            sourceCategory: "유박류",
            selectionGroup: .tmr,
            category: .concentrate,
            defaultPriceKrwPerKg: 620,
            nutrition: IngredientNutritionProfile(
                moisturePct: 5.87,
                dmPct: 94.13,
                cpPctDm: 42.48,
                tdnPctDm: 67.55,
                ndfPctDm: 51.01,
                adfPctDm: 29.94,
                nfcPctDm: 0.0,
                eePctDm: 9.38,
                ashPctDm: 6.71,
                caPctDm: 0.82,
                pPctDm: 1.14
            )
        ),
        IngredientDefinition(
            id: "FEED_27",
            sourceFeedNo: 27,
            name: "맥주박",
            sourceCategory: "유박류",
            selectionGroup: .tmr,
            category: .concentrate,
            defaultPriceKrwPerKg: 620,
            nutrition: IngredientNutritionProfile(
                moisturePct: 65.34,
                dmPct: 34.66,
                cpPctDm: 23.22,
                tdnPctDm: 71.98,
                ndfPctDm: 57.92,
                adfPctDm: 27.05,
                nfcPctDm: 7.29,
                eePctDm: 6.4,
                ashPctDm: 5.14,
                caPctDm: 0.3,
                pPctDm: 0.6
            )
        ),
        IngredientDefinition(
            id: "FEED_28",
            sourceFeedNo: 28,
            name: "밀주정박",
            sourceCategory: "유박류",
            selectionGroup: .tmr,
            category: .concentrate,
            defaultPriceKrwPerKg: 620,
            nutrition: IngredientNutritionProfile(
                moisturePct: 7.74,
                dmPct: 92.26,
                cpPctDm: 35.8,
                tdnPctDm: 73.1,
                ndfPctDm: 29.29,
                adfPctDm: 12.91,
                nfcPctDm: 23.38,
                eePctDm: 5.89,
                ashPctDm: 5.62,
                caPctDm: 0.13,
                pPctDm: 0.92
            )
        ),
        IngredientDefinition(
            id: "FEED_29",
            sourceFeedNo: 29,
            name: "아마박",
            sourceCategory: "유박류",
            selectionGroup: .tmr,
            category: .concentrate,
            defaultPriceKrwPerKg: 620,
            nutrition: IngredientNutritionProfile(
                moisturePct: 8.92,
                dmPct: 91.08,
                cpPctDm: 35.21,
                tdnPctDm: 73.6,
                ndfPctDm: 42.0,
                adfPctDm: 21.76,
                nfcPctDm: 2.78,
                eePctDm: 14.56,
                ashPctDm: 5.43,
                caPctDm: 0.3,
                pPctDm: 0.72
            )
        ),
        IngredientDefinition(
            id: "FEED_30",
            sourceFeedNo: 30,
            name: "아몬드박",
            sourceCategory: "유박류",
            selectionGroup: .tmr,
            category: .concentrate,
            defaultPriceKrwPerKg: 620,
            nutrition: IngredientNutritionProfile(
                moisturePct: 9.3,
                dmPct: 90.7,
                cpPctDm: 14.37,
                tdnPctDm: 57.02,
                ndfPctDm: 56.06,
                adfPctDm: 42.8,
                nfcPctDm: 16.88,
                eePctDm: 7.22,
                ashPctDm: 5.44,
                caPctDm: 0.34,
                pPctDm: 0.3
            )
        ),
        IngredientDefinition(
            id: "FEED_31",
            sourceFeedNo: 31,
            name: "옥수수글루텐밀",
            sourceCategory: "유박류",
            selectionGroup: .tmr,
            category: .concentrate,
            defaultPriceKrwPerKg: 620,
            nutrition: IngredientNutritionProfile(
                moisturePct: 8.55,
                dmPct: 91.45,
                cpPctDm: 72.0,
                tdnPctDm: 85.82,
                ndfPctDm: 16.71,
                adfPctDm: 7.41,
                nfcPctDm: 6.45,
                eePctDm: 2.01,
                ashPctDm: 2.81,
                caPctDm: 0.02,
                pPctDm: 0.43
            )
        ),
        IngredientDefinition(
            id: "FEED_32",
            sourceFeedNo: 32,
            name: "옥수수배아박",
            sourceCategory: "유박류",
            selectionGroup: .tmr,
            category: .concentrate,
            defaultPriceKrwPerKg: 620,
            nutrition: IngredientNutritionProfile(
                moisturePct: 8.91,
                dmPct: 91.09,
                cpPctDm: 22.82,
                tdnPctDm: 82.1,
                ndfPctDm: 43.84,
                adfPctDm: 10.93,
                nfcPctDm: 18.76,
                eePctDm: 11.77,
                ashPctDm: 2.78,
                caPctDm: 0.03,
                pPctDm: 0.69
            )
        ),
        IngredientDefinition(
            id: "FEED_33",
            sourceFeedNo: 33,
            name: "옥수수 주정박",
            sourceCategory: "유박류",
            selectionGroup: .tmr,
            category: .concentrate,
            defaultPriceKrwPerKg: 620,
            nutrition: IngredientNutritionProfile(
                moisturePct: 10.91,
                dmPct: 89.09,
                cpPctDm: 30.87,
                tdnPctDm: 89.0,
                ndfPctDm: 39.05,
                adfPctDm: 11.11,
                nfcPctDm: 14.11,
                eePctDm: 10.67,
                ashPctDm: 5.29,
                caPctDm: 0.07,
                pPctDm: 1.0
            )
        ),
        IngredientDefinition(
            id: "FEED_34",
            sourceFeedNo: 34,
            name: "장유박",
            sourceCategory: "유박류",
            selectionGroup: .tmr,
            category: .concentrate,
            defaultPriceKrwPerKg: 620,
            nutrition: IngredientNutritionProfile(
                moisturePct: 25.21,
                dmPct: 74.79,
                cpPctDm: 33.95,
                tdnPctDm: 69.6,
                ndfPctDm: 34.49,
                adfPctDm: 21.85,
                nfcPctDm: 12.47,
                eePctDm: 7.06,
                ashPctDm: 12.0,
                caPctDm: 0.56,
                pPctDm: 0.15
            )
        ),
        IngredientDefinition(
            id: "FEED_35",
            sourceFeedNo: 35,
            name: "전분박",
            sourceCategory: "유박류",
            selectionGroup: .tmr,
            category: .concentrate,
            defaultPriceKrwPerKg: 620,
            nutrition: IngredientNutritionProfile(
                moisturePct: 12.77,
                dmPct: 87.23,
                cpPctDm: 11.91,
                tdnPctDm: 67.83,
                ndfPctDm: 0.0,
                adfPctDm: 0.0,
                nfcPctDm: 0.0,
                eePctDm: 1.73,
                ashPctDm: 5.35,
                caPctDm: 0.03,
                pPctDm: 0.26
            )
        ),
        IngredientDefinition(
            id: "FEED_36",
            sourceFeedNo: 36,
            name: "감귤박(생)",
            sourceCategory: "유박류",
            selectionGroup: .tmr,
            category: .concentrate,
            defaultPriceKrwPerKg: 620,
            nutrition: IngredientNutritionProfile(
                moisturePct: 84.95,
                dmPct: 15.05,
                cpPctDm: 9.1,
                tdnPctDm: 70.0,
                ndfPctDm: 41.42,
                adfPctDm: 34.41,
                nfcPctDm: 40.8,
                eePctDm: 5.78,
                ashPctDm: 2.88,
                caPctDm: 0.54,
                pPctDm: 0.09
            )
        ),
        IngredientDefinition(
            id: "FEED_37",
            sourceFeedNo: 37,
            name: "당밀",
            sourceCategory: "농식품부산물",
            selectionGroup: .tmr,
            category: .agriByproduct,
            defaultPriceKrwPerKg: 180,
            nutrition: IngredientNutritionProfile(
                moisturePct: 19.39,
                dmPct: 80.61,
                cpPctDm: 8.79,
                tdnPctDm: 84.29,
                ndfPctDm: 0.3,
                adfPctDm: 0.5,
                nfcPctDm: 79.31,
                eePctDm: 0.73,
                ashPctDm: 10.85,
                caPctDm: 0.91,
                pPctDm: 0.07
            )
        ),
        IngredientDefinition(
            id: "FEED_38",
            sourceFeedNo: 38,
            name: "도토리박",
            sourceCategory: "농식품부산물",
            selectionGroup: .tmr,
            category: .agriByproduct,
            defaultPriceKrwPerKg: 180,
            nutrition: IngredientNutritionProfile(
                moisturePct: 62.08,
                dmPct: 37.92,
                cpPctDm: 4.96,
                tdnPctDm: 68.94,
                ndfPctDm: 65.92,
                adfPctDm: 39.55,
                nfcPctDm: 16.82,
                eePctDm: 0.73,
                ashPctDm: 1.43,
                caPctDm: 0.02,
                pPctDm: 0.26
            )
        ),
        IngredientDefinition(
            id: "FEED_39",
            sourceFeedNo: 39,
            name: "땅콩피",
            sourceCategory: "농식품부산물",
            selectionGroup: .tmr,
            category: .agriByproduct,
            defaultPriceKrwPerKg: 180,
            nutrition: IngredientNutritionProfile(
                moisturePct: 9.7,
                dmPct: 90.3,
                cpPctDm: 8.1,
                tdnPctDm: 42.76,
                ndfPctDm: 82.29,
                adfPctDm: 74.65,
                nfcPctDm: 3.33,
                eePctDm: 0.69,
                ashPctDm: 5.57,
                caPctDm: 0.44,
                pPctDm: 0.07
            )
        ),
        IngredientDefinition(
            id: "FEED_40",
            sourceFeedNo: 40,
            name: "라면부스러기",
            sourceCategory: "농식품부산물",
            selectionGroup: .tmr,
            category: .agriByproduct,
            defaultPriceKrwPerKg: 180,
            nutrition: IngredientNutritionProfile(
                moisturePct: 11.26,
                dmPct: 88.74,
                cpPctDm: 9.03,
                tdnPctDm: 88.53,
                ndfPctDm: 12.86,
                adfPctDm: 2.15,
                nfcPctDm: 63.3,
                eePctDm: 10.76,
                ashPctDm: 4.02,
                caPctDm: 0.07,
                pPctDm: 0.11
            )
        ),
        IngredientDefinition(
            id: "FEED_41",
            sourceFeedNo: 41,
            name: "배추부산물",
            sourceCategory: "농식품부산물",
            selectionGroup: .tmr,
            category: .agriByproduct,
            defaultPriceKrwPerKg: 180,
            nutrition: IngredientNutritionProfile(
                moisturePct: 91.55,
                dmPct: 8.45,
                cpPctDm: 18.92,
                tdnPctDm: 72.87,
                ndfPctDm: 27.64,
                adfPctDm: 21.99,
                nfcPctDm: 2.33,
                eePctDm: 1.98,
                ashPctDm: 17.87,
                caPctDm: 1.62,
                pPctDm: 0.55
            )
        ),
        IngredientDefinition(
            id: "FEED_42",
            sourceFeedNo: 42,
            name: "버섯재배부산물(느타리)",
            sourceCategory: "농식품부산물",
            selectionGroup: .tmr,
            category: .agriByproduct,
            defaultPriceKrwPerKg: 180,
            nutrition: IngredientNutritionProfile(
                moisturePct: 63.02,
                dmPct: 36.98,
                cpPctDm: 10.47,
                tdnPctDm: 47.59,
                ndfPctDm: 67.82,
                adfPctDm: 53.3,
                nfcPctDm: 13.68,
                eePctDm: 0.91,
                ashPctDm: 7.1,
                caPctDm: 2.52,
                pPctDm: 0.47
            )
        ),
        IngredientDefinition(
            id: "FEED_43",
            sourceFeedNo: 43,
            name: "버섯재배부산물(팽이)",
            sourceCategory: "농식품부산물",
            selectionGroup: .tmr,
            category: .agriByproduct,
            defaultPriceKrwPerKg: 180,
            nutrition: IngredientNutritionProfile(
                moisturePct: 54.46,
                dmPct: 45.54,
                cpPctDm: 9.37,
                tdnPctDm: 51.59,
                ndfPctDm: 57.26,
                adfPctDm: 34.67,
                nfcPctDm: 16.46,
                eePctDm: 6.16,
                ashPctDm: 10.73,
                caPctDm: 2.44,
                pPctDm: 0.12
            )
        ),
        IngredientDefinition(
            id: "FEED_44",
            sourceFeedNo: 44,
            name: "버섯재배부산물(새송이)",
            sourceCategory: "농식품부산물",
            selectionGroup: .tmr,
            category: .agriByproduct,
            defaultPriceKrwPerKg: 180,
            nutrition: IngredientNutritionProfile(
                moisturePct: 59.19,
                dmPct: 40.81,
                cpPctDm: 9.02,
                tdnPctDm: 43.69,
                ndfPctDm: 72.43,
                adfPctDm: 64.2,
                nfcPctDm: 8.48,
                eePctDm: 1.55,
                ashPctDm: 8.5,
                caPctDm: 0.05,
                pPctDm: 0.45
            )
        ),
        IngredientDefinition(
            id: "FEED_45",
            sourceFeedNo: 45,
            name: "비지(두부박)",
            sourceCategory: "농식품부산물",
            selectionGroup: .tmr,
            category: .agriByproduct,
            defaultPriceKrwPerKg: 180,
            nutrition: IngredientNutritionProfile(
                moisturePct: 80.84,
                dmPct: 19.16,
                cpPctDm: 20.18,
                tdnPctDm: 74.64,
                ndfPctDm: 35.44,
                adfPctDm: 24.28,
                nfcPctDm: 35.49,
                eePctDm: 5.29,
                ashPctDm: 3.58,
                caPctDm: 0.31,
                pPctDm: 0.35
            )
        ),
        IngredientDefinition(
            id: "FEED_46",
            sourceFeedNo: 46,
            name: "엿밥",
            sourceCategory: "농식품부산물",
            selectionGroup: .tmr,
            category: .agriByproduct,
            defaultPriceKrwPerKg: 180,
            nutrition: IngredientNutritionProfile(
                moisturePct: 45.12,
                dmPct: 54.88,
                cpPctDm: 34.67,
                tdnPctDm: 74.76,
                ndfPctDm: 32.03,
                adfPctDm: 18.2,
                nfcPctDm: 22.56,
                eePctDm: 5.67,
                ashPctDm: 5.05,
                caPctDm: 0.0,
                pPctDm: 0.0
            )
        ),
        IngredientDefinition(
            id: "FEED_47",
            sourceFeedNo: 47,
            name: "자두박",
            sourceCategory: "농식품부산물",
            selectionGroup: .tmr,
            category: .agriByproduct,
            defaultPriceKrwPerKg: 180,
            nutrition: IngredientNutritionProfile(
                moisturePct: 9.8,
                dmPct: 90.2,
                cpPctDm: 11.11,
                tdnPctDm: 72.01,
                ndfPctDm: 62.38,
                adfPctDm: 43.89,
                nfcPctDm: 15.21,
                eePctDm: 6.35,
                ashPctDm: 4.93,
                caPctDm: 0.21,
                pPctDm: 0.49
            )
        ),
        IngredientDefinition(
            id: "FEED_48",
            sourceFeedNo: 48,
            name: "제과부산물",
            sourceCategory: "농식품부산물",
            selectionGroup: .tmr,
            category: .agriByproduct,
            defaultPriceKrwPerKg: 180,
            nutrition: IngredientNutritionProfile(
                moisturePct: 7.42,
                dmPct: 92.58,
                cpPctDm: 7.74,
                tdnPctDm: 91.9,
                ndfPctDm: 14.91,
                adfPctDm: 10.81,
                nfcPctDm: 61.18,
                eePctDm: 12.43,
                ashPctDm: 3.72,
                caPctDm: 0.1,
                pPctDm: 0.15
            )
        ),
        IngredientDefinition(
            id: "FEED_49",
            sourceFeedNo: 49,
            name: "제빵부산물",
            sourceCategory: "농식품부산물",
            selectionGroup: .tmr,
            category: .agriByproduct,
            defaultPriceKrwPerKg: 180,
            nutrition: IngredientNutritionProfile(
                moisturePct: 7.68,
                dmPct: 92.32,
                cpPctDm: 8.7,
                tdnPctDm: 90.6,
                ndfPctDm: 10.08,
                adfPctDm: 6.96,
                nfcPctDm: 64.36,
                eePctDm: 13.8,
                ashPctDm: 3.03,
                caPctDm: 0.15,
                pPctDm: 0.21
            )
        ),
        IngredientDefinition(
            id: "FEED_51",
            sourceFeedNo: 51,
            name: "파인애플박",
            sourceCategory: "농식품부산물",
            selectionGroup: .tmr,
            category: .agriByproduct,
            defaultPriceKrwPerKg: 180,
            nutrition: IngredientNutritionProfile(
                moisturePct: 75.33,
                dmPct: 24.67,
                cpPctDm: 7.19,
                tdnPctDm: 49.99,
                ndfPctDm: 67.54,
                adfPctDm: 33.93,
                nfcPctDm: 19.57,
                eePctDm: 0.32,
                ashPctDm: 5.36,
                caPctDm: 0.5,
                pPctDm: 0.5
            )
        ),
        IngredientDefinition(
            id: "FEED_52",
            sourceFeedNo: 52,
            name: "포도씨박",
            sourceCategory: "농식품부산물",
            selectionGroup: .tmr,
            category: .agriByproduct,
            defaultPriceKrwPerKg: 180,
            nutrition: IngredientNutritionProfile(
                moisturePct: 10.45,
                dmPct: 89.55,
                cpPctDm: 11.82,
                tdnPctDm: 47.0,
                ndfPctDm: 58.65,
                adfPctDm: 45.58,
                nfcPctDm: 15.32,
                eePctDm: 6.88,
                ashPctDm: 7.31,
                caPctDm: 0.5,
                pPctDm: 0.32
            )
        ),
        IngredientDefinition(
            id: "FEED_53",
            sourceFeedNo: 53,
            name: "홍삼박",
            sourceCategory: "농식품부산물",
            selectionGroup: .tmr,
            category: .agriByproduct,
            defaultPriceKrwPerKg: 180,
            nutrition: IngredientNutritionProfile(
                moisturePct: 8.52,
                dmPct: 91.48,
                cpPctDm: 15.01,
                tdnPctDm: 79.08,
                ndfPctDm: 48.25,
                adfPctDm: 28.61,
                nfcPctDm: 32.45,
                eePctDm: 0.71,
                ashPctDm: 3.56,
                caPctDm: 1.04,
                pPctDm: 0.09
            )
        ),
        IngredientDefinition(
            id: "FEED_54",
            sourceFeedNo: 54,
            name: "레드클로버(붉은토끼풀)",
            sourceCategory: "목초",
            selectionGroup: .tmr,
            category: .roughage,
            defaultPriceKrwPerKg: 620,
            nutrition: IngredientNutritionProfile(
                moisturePct: 74.7,
                dmPct: 25.3,
                cpPctDm: 20.55,
                tdnPctDm: 65.69,
                ndfPctDm: 36.4,
                adfPctDm: 26.6,
                nfcPctDm: 22.88,
                eePctDm: 6.32,
                ashPctDm: 13.83,
                caPctDm: 0.15,
                pPctDm: 0.37
            )
        ),
        IngredientDefinition(
            id: "FEED_55",
            sourceFeedNo: 55,
            name: "리드카나리그라스",
            sourceCategory: "목초",
            selectionGroup: .tmr,
            category: .roughage,
            defaultPriceKrwPerKg: 620,
            nutrition: IngredientNutritionProfile(
                moisturePct: 89.14,
                dmPct: 10.86,
                cpPctDm: 14.16,
                tdnPctDm: 57.61,
                ndfPctDm: 64.16,
                adfPctDm: 30.09,
                nfcPctDm: 11.24,
                eePctDm: 3.45,
                ashPctDm: 6.98,
                caPctDm: 0.19,
                pPctDm: 0.32
            )
        ),
        IngredientDefinition(
            id: "FEED_56",
            sourceFeedNo: 56,
            name: "알팔파 펠렛",
            sourceCategory: "목초",
            selectionGroup: .tmr,
            category: .roughage,
            defaultPriceKrwPerKg: 620,
            nutrition: IngredientNutritionProfile(
                moisturePct: 9.27,
                dmPct: 90.73,
                cpPctDm: 15.53,
                tdnPctDm: 56.0,
                ndfPctDm: 53.9,
                adfPctDm: 37.19,
                nfcPctDm: 16.55,
                eePctDm: 1.83,
                ashPctDm: 12.17,
                caPctDm: 1.52,
                pPctDm: 0.25
            )
        ),
        IngredientDefinition(
            id: "FEED_57",
            sourceFeedNo: 57,
            name: "연맥 목초",
            sourceCategory: "목초",
            selectionGroup: .tmr,
            category: .roughage,
            defaultPriceKrwPerKg: 620,
            nutrition: IngredientNutritionProfile(
                moisturePct: 10.54,
                dmPct: 89.46,
                cpPctDm: 7.62,
                tdnPctDm: 65.64,
                ndfPctDm: 64.06,
                adfPctDm: 40.33,
                nfcPctDm: 19.67,
                eePctDm: 1.46,
                ashPctDm: 7.17,
                caPctDm: 0.19,
                pPctDm: 0.2
            )
        ),
        IngredientDefinition(
            id: "FEED_58",
            sourceFeedNo: 58,
            name: "귀리짚(연맥짚)",
            sourceCategory: "고간류",
            selectionGroup: .tmr,
            category: .roughage,
            defaultPriceKrwPerKg: 210,
            nutrition: IngredientNutritionProfile(
                moisturePct: 9.96,
                dmPct: 90.04,
                cpPctDm: 5.12,
                tdnPctDm: 51.34,
                ndfPctDm: 64.01,
                adfPctDm: 40.66,
                nfcPctDm: 23.31,
                eePctDm: 1.42,
                ashPctDm: 6.12,
                caPctDm: 0.2,
                pPctDm: 0.16
            )
        ),
        IngredientDefinition(
            id: "FEED_59",
            sourceFeedNo: 59,
            name: "밀짚",
            sourceCategory: "고간류",
            selectionGroup: .tmr,
            category: .roughage,
            defaultPriceKrwPerKg: 210,
            nutrition: IngredientNutritionProfile(
                moisturePct: 10.51,
                dmPct: 89.49,
                cpPctDm: 3.77,
                tdnPctDm: 50.04,
                ndfPctDm: 64.84,
                adfPctDm: 43.89,
                nfcPctDm: 23.48,
                eePctDm: 1.0,
                ashPctDm: 6.88,
                caPctDm: 0.25,
                pPctDm: 0.07
            )
        ),
        IngredientDefinition(
            id: "FEED_60",
            sourceFeedNo: 60,
            name: "볏짚(사일리지)",
            sourceCategory: "고간류",
            selectionGroup: .tmr,
            category: .roughage,
            defaultPriceKrwPerKg: 210,
            nutrition: IngredientNutritionProfile(
                moisturePct: 39.13,
                dmPct: 60.87,
                cpPctDm: 4.17,
                tdnPctDm: 45.76,
                ndfPctDm: 68.96,
                adfPctDm: 44.2,
                nfcPctDm: 13.71,
                eePctDm: 1.05,
                ashPctDm: 12.08,
                caPctDm: 0.25,
                pPctDm: 0.1
            )
        ),
        IngredientDefinition(
            id: "FEED_61",
            sourceFeedNo: 61,
            name: "보릿짚",
            sourceCategory: "고간류",
            selectionGroup: .tmr,
            category: .roughage,
            defaultPriceKrwPerKg: 210,
            nutrition: IngredientNutritionProfile(
                moisturePct: 9.48,
                dmPct: 90.52,
                cpPctDm: 2.96,
                tdnPctDm: 48.14,
                ndfPctDm: 76.33,
                adfPctDm: 50.78,
                nfcPctDm: 14.89,
                eePctDm: 0.77,
                ashPctDm: 5.03,
                caPctDm: 0.38,
                pPctDm: 0.11
            )
        ),
        IngredientDefinition(
            id: "FEED_62",
            sourceFeedNo: 62,
            name: "알팔파 짚",
            sourceCategory: "고간류",
            selectionGroup: .tmr,
            category: .roughage,
            defaultPriceKrwPerKg: 210,
            nutrition: IngredientNutritionProfile(
                moisturePct: 9.48,
                dmPct: 90.52,
                cpPctDm: 13.25,
                tdnPctDm: 52.4,
                ndfPctDm: 56.28,
                adfPctDm: 40.38,
                nfcPctDm: 18.65,
                eePctDm: 1.57,
                ashPctDm: 10.22,
                caPctDm: 1.15,
                pPctDm: 0.23
            )
        ),
        IngredientDefinition(
            id: "FEED_63",
            sourceFeedNo: 63,
            name: "애뉴얼라이그라스 짚",
            sourceCategory: "고간류",
            selectionGroup: .tmr,
            category: .roughage,
            defaultPriceKrwPerKg: 210,
            nutrition: IngredientNutritionProfile(
                moisturePct: 8.69,
                dmPct: 91.31,
                cpPctDm: 5.07,
                tdnPctDm: 51.5,
                ndfPctDm: 72.32,
                adfPctDm: 47.93,
                nfcPctDm: 16.48,
                eePctDm: 0.82,
                ashPctDm: 5.29,
                caPctDm: 0.33,
                pPctDm: 0.08
            )
        ),
        IngredientDefinition(
            id: "FEED_64",
            sourceFeedNo: 64,
            name: "오차드그라스 짚",
            sourceCategory: "고간류",
            selectionGroup: .tmr,
            category: .roughage,
            defaultPriceKrwPerKg: 210,
            nutrition: IngredientNutritionProfile(
                moisturePct: 9.32,
                dmPct: 90.68,
                cpPctDm: 5.63,
                tdnPctDm: 46.5,
                ndfPctDm: 75.18,
                adfPctDm: 50.5,
                nfcPctDm: 11.99,
                eePctDm: 1.32,
                ashPctDm: 5.85,
                caPctDm: 0.25,
                pPctDm: 0.11
            )
        ),
        IngredientDefinition(
            id: "FEED_65",
            sourceFeedNo: 65,
            name: "옥수수대",
            sourceCategory: "고간류",
            selectionGroup: .tmr,
            category: .roughage,
            defaultPriceKrwPerKg: 210,
            nutrition: IngredientNutritionProfile(
                moisturePct: 10.17,
                dmPct: 89.83,
                cpPctDm: 4.95,
                tdnPctDm: 44.43,
                ndfPctDm: 73.72,
                adfPctDm: 49.46,
                nfcPctDm: 0.0,
                eePctDm: 0.81,
                ashPctDm: 22.56,
                caPctDm: 0.44,
                pPctDm: 0.1
            )
        ),
        IngredientDefinition(
            id: "FEED_66",
            sourceFeedNo: 66,
            name: "티모시 짚",
            sourceCategory: "고간류",
            selectionGroup: .tmr,
            category: .roughage,
            defaultPriceKrwPerKg: 210,
            nutrition: IngredientNutritionProfile(
                moisturePct: 8.47,
                dmPct: 91.53,
                cpPctDm: 6.1,
                tdnPctDm: 49.39,
                ndfPctDm: 68.65,
                adfPctDm: 43.6,
                nfcPctDm: 18.33,
                eePctDm: 1.25,
                ashPctDm: 5.65,
                caPctDm: 0.22,
                pPctDm: 0.16
            )
        ),
        IngredientDefinition(
            id: "FEED_67",
            sourceFeedNo: 67,
            name: "페레니얼라이그라스 짚",
            sourceCategory: "고간류",
            selectionGroup: .tmr,
            category: .roughage,
            defaultPriceKrwPerKg: 210,
            nutrition: IngredientNutritionProfile(
                moisturePct: 20.46,
                dmPct: 79.54,
                cpPctDm: 5.46,
                tdnPctDm: 43.42,
                ndfPctDm: 68.74,
                adfPctDm: 43.94,
                nfcPctDm: 17.13,
                eePctDm: 0.92,
                ashPctDm: 7.72,
                caPctDm: 0.31,
                pPctDm: 0.19
            )
        ),
        IngredientDefinition(
            id: "FEED_68",
            sourceFeedNo: 68,
            name: "보리사일리지(호숙기)",
            sourceCategory: "사일리지 및 청예조사료",
            selectionGroup: .tmr,
            category: .roughage,
            defaultPriceKrwPerKg: 180,
            nutrition: IngredientNutritionProfile(
                moisturePct: 60.0,
                dmPct: 40.0,
                cpPctDm: 14.11,
                tdnPctDm: 56.83,
                ndfPctDm: 50.74,
                adfPctDm: 32.91,
                nfcPctDm: 16.72,
                eePctDm: 3.94,
                ashPctDm: 14.47,
                caPctDm: 1.71,
                pPctDm: 1.33
            )
        ),
        IngredientDefinition(
            id: "FEED_69",
            sourceFeedNo: 69,
            name: "보리사일리지(황숙기)",
            sourceCategory: "사일리지 및 청예조사료",
            selectionGroup: .tmr,
            category: .roughage,
            defaultPriceKrwPerKg: 180,
            nutrition: IngredientNutritionProfile(
                moisturePct: 60.0,
                dmPct: 40.0,
                cpPctDm: 7.73,
                tdnPctDm: 55.1,
                ndfPctDm: 59.54,
                adfPctDm: 36.31,
                nfcPctDm: 23.42,
                eePctDm: 3.66,
                ashPctDm: 5.64,
                caPctDm: 0.13,
                pPctDm: 0.89
            )
        ),
        IngredientDefinition(
            id: "FEED_70",
            sourceFeedNo: 70,
            name: "수수수단그라스사일리지(개화기)",
            sourceCategory: "사일리지 및 청예조사료",
            selectionGroup: .tmr,
            category: .roughage,
            defaultPriceKrwPerKg: 180,
            nutrition: IngredientNutritionProfile(
                moisturePct: 70.0,
                dmPct: 30.0,
                cpPctDm: 7.22,
                tdnPctDm: 55.57,
                ndfPctDm: 65.92,
                adfPctDm: 41.69,
                nfcPctDm: 15.24,
                eePctDm: 3.22,
                ashPctDm: 8.38,
                caPctDm: 0.33,
                pPctDm: 0.44
            )
        ),
        IngredientDefinition(
            id: "FEED_71",
            sourceFeedNo: 71,
            name: "수수수단그라스사일리지(출수기)",
            sourceCategory: "사일리지 및 청예조사료",
            selectionGroup: .tmr,
            category: .roughage,
            defaultPriceKrwPerKg: 180,
            nutrition: IngredientNutritionProfile(
                moisturePct: 70.0,
                dmPct: 30.0,
                cpPctDm: 10.05,
                tdnPctDm: 55.7,
                ndfPctDm: 61.73,
                adfPctDm: 38.52,
                nfcPctDm: 16.59,
                eePctDm: 3.22,
                ashPctDm: 8.38,
                caPctDm: 0.38,
                pPctDm: 0.23
            )
        ),
        IngredientDefinition(
            id: "FEED_72",
            sourceFeedNo: 72,
            name: "옥수수사일리지(황숙기)",
            sourceCategory: "사일리지 및 청예조사료",
            selectionGroup: .tmr,
            category: .roughage,
            defaultPriceKrwPerKg: 180,
            nutrition: IngredientNutritionProfile(
                moisturePct: 70.0,
                dmPct: 30.0,
                cpPctDm: 9.54,
                tdnPctDm: 63.66,
                ndfPctDm: 48.63,
                adfPctDm: 30.59,
                nfcPctDm: 29.87,
                eePctDm: 3.02,
                ashPctDm: 8.92,
                caPctDm: 0.09,
                pPctDm: 0.27
            )
        ),
        IngredientDefinition(
            id: "FEED_73",
            sourceFeedNo: 73,
            name: "이탈리안라이그라스사일리지(출수기)",
            sourceCategory: "사일리지 및 청예조사료",
            selectionGroup: .tmr,
            category: .roughage,
            defaultPriceKrwPerKg: 180,
            nutrition: IngredientNutritionProfile(
                moisturePct: 60.0,
                dmPct: 40.0,
                cpPctDm: 10.71,
                tdnPctDm: 62.7,
                ndfPctDm: 56.4,
                adfPctDm: 36.18,
                nfcPctDm: 21.68,
                eePctDm: 2.85,
                ashPctDm: 7.61,
                caPctDm: 0.34,
                pPctDm: 0.38
            )
        ),
        IngredientDefinition(
            id: "FEED_74",
            sourceFeedNo: 74,
            name: "청예보리(호숙기)",
            sourceCategory: "사일리지 및 청예조사료",
            selectionGroup: .tmr,
            category: .roughage,
            defaultPriceKrwPerKg: 180,
            nutrition: IngredientNutritionProfile(
                moisturePct: 74.3,
                dmPct: 25.7,
                cpPctDm: 9.63,
                tdnPctDm: 59.52,
                ndfPctDm: 49.43,
                adfPctDm: 30.2,
                nfcPctDm: 29.85,
                eePctDm: 2.69,
                ashPctDm: 8.38,
                caPctDm: 0.39,
                pPctDm: 0.35
            )
        ),
        IngredientDefinition(
            id: "FEED_75",
            sourceFeedNo: 75,
            name: "청예보리(황숙기)",
            sourceCategory: "사일리지 및 청예조사료",
            selectionGroup: .tmr,
            category: .roughage,
            defaultPriceKrwPerKg: 180,
            nutrition: IngredientNutritionProfile(
                moisturePct: 57.23,
                dmPct: 42.77,
                cpPctDm: 9.58,
                tdnPctDm: 55.29,
                ndfPctDm: 48.44,
                adfPctDm: 28.03,
                nfcPctDm: 31.84,
                eePctDm: 3.66,
                ashPctDm: 6.46,
                caPctDm: 0.42,
                pPctDm: 0.39
            )
        ),
        IngredientDefinition(
            id: "FEED_76",
            sourceFeedNo: 76,
            name: "청예수수수단그라스(개화기)",
            sourceCategory: "사일리지 및 청예조사료",
            selectionGroup: .tmr,
            category: .roughage,
            defaultPriceKrwPerKg: 180,
            nutrition: IngredientNutritionProfile(
                moisturePct: 73.96,
                dmPct: 26.04,
                cpPctDm: 7.1,
                tdnPctDm: 55.57,
                ndfPctDm: 66.15,
                adfPctDm: 43.39,
                nfcPctDm: 13.2,
                eePctDm: 4.51,
                ashPctDm: 9.02,
                caPctDm: 0.32,
                pPctDm: 0.32
            )
        ),
        IngredientDefinition(
            id: "FEED_77",
            sourceFeedNo: 77,
            name: "청예수수수단그라스(출수기)",
            sourceCategory: "사일리지 및 청예조사료",
            selectionGroup: .tmr,
            category: .roughage,
            defaultPriceKrwPerKg: 180,
            nutrition: IngredientNutritionProfile(
                moisturePct: 83.76,
                dmPct: 16.24,
                cpPctDm: 8.59,
                tdnPctDm: 55.57,
                ndfPctDm: 65.96,
                adfPctDm: 42.65,
                nfcPctDm: 14.8,
                eePctDm: 1.59,
                ashPctDm: 9.04,
                caPctDm: 0.38,
                pPctDm: 0.23
            )
        ),
        IngredientDefinition(
            id: "FEED_78",
            sourceFeedNo: 78,
            name: "청예옥수수(유숙기)",
            sourceCategory: "사일리지 및 청예조사료",
            selectionGroup: .tmr,
            category: .roughage,
            defaultPriceKrwPerKg: 180,
            nutrition: IngredientNutritionProfile(
                moisturePct: 81.73,
                dmPct: 18.27,
                cpPctDm: 9.37,
                tdnPctDm: 70.66,
                ndfPctDm: 61.97,
                adfPctDm: 36.15,
                nfcPctDm: 19.41,
                eePctDm: 3.07,
                ashPctDm: 6.15,
                caPctDm: 0.21,
                pPctDm: 0.35
            )
        ),
        IngredientDefinition(
            id: "FEED_79",
            sourceFeedNo: 79,
            name: "청예옥수수(출수기)",
            sourceCategory: "사일리지 및 청예조사료",
            selectionGroup: .tmr,
            category: .roughage,
            defaultPriceKrwPerKg: 180,
            nutrition: IngredientNutritionProfile(
                moisturePct: 80.76,
                dmPct: 19.24,
                cpPctDm: 10.87,
                tdnPctDm: 69.22,
                ndfPctDm: 67.52,
                adfPctDm: 40.94,
                nfcPctDm: 12.71,
                eePctDm: 1.94,
                ashPctDm: 6.93,
                caPctDm: 0.21,
                pPctDm: 0.35
            )
        ),
        IngredientDefinition(
            id: "FEED_80",
            sourceFeedNo: 80,
            name: "청예옥수수(호숙기)",
            sourceCategory: "사일리지 및 청예조사료",
            selectionGroup: .tmr,
            category: .roughage,
            defaultPriceKrwPerKg: 180,
            nutrition: IngredientNutritionProfile(
                moisturePct: 67.46,
                dmPct: 32.54,
                cpPctDm: 7.57,
                tdnPctDm: 71.44,
                ndfPctDm: 60.49,
                adfPctDm: 36.87,
                nfcPctDm: 23.17,
                eePctDm: 2.76,
                ashPctDm: 5.99,
                caPctDm: 0.17,
                pPctDm: 0.26
            )
        ),
        IngredientDefinition(
            id: "FEED_81",
            sourceFeedNo: 81,
            name: "청예옥수수(황숙기)",
            sourceCategory: "사일리지 및 청예조사료",
            selectionGroup: .tmr,
            category: .roughage,
            defaultPriceKrwPerKg: 180,
            nutrition: IngredientNutritionProfile(
                moisturePct: 64.03,
                dmPct: 35.97,
                cpPctDm: 6.26,
                tdnPctDm: 68.5,
                ndfPctDm: 66.34,
                adfPctDm: 40.56,
                nfcPctDm: 19.7,
                eePctDm: 1.69,
                ashPctDm: 5.99,
                caPctDm: 0.17,
                pPctDm: 0.26
            )
        ),
        IngredientDefinition(
            id: "FEED_82",
            sourceFeedNo: 82,
            name: "청예이탈리안라이그라스(개화후기)",
            sourceCategory: "사일리지 및 청예조사료",
            selectionGroup: .tmr,
            category: .roughage,
            defaultPriceKrwPerKg: 180,
            nutrition: IngredientNutritionProfile(
                moisturePct: 76.9,
                dmPct: 23.1,
                cpPctDm: 9.31,
                tdnPctDm: 57.62,
                ndfPctDm: 59.15,
                adfPctDm: 35.75,
                nfcPctDm: 17.96,
                eePctDm: 3.81,
                ashPctDm: 9.74,
                caPctDm: 1.67,
                pPctDm: 0.27
            )
        ),
        IngredientDefinition(
            id: "FEED_83",
            sourceFeedNo: 83,
            name: "청예이탈리안라이그라스(출수기)",
            sourceCategory: "사일리지 및 청예조사료",
            selectionGroup: .tmr,
            category: .roughage,
            defaultPriceKrwPerKg: 180,
            nutrition: IngredientNutritionProfile(
                moisturePct: 80.53,
                dmPct: 19.47,
                cpPctDm: 11.98,
                tdnPctDm: 63.67,
                ndfPctDm: 53.47,
                adfPctDm: 32.37,
                nfcPctDm: 23.52,
                eePctDm: 2.85,
                ashPctDm: 8.16,
                caPctDm: 1.76,
                pPctDm: 1.03
            )
        ),
        IngredientDefinition(
            id: "FEED_84",
            sourceFeedNo: 84,
            name: "청예호밀(개화기)",
            sourceCategory: "사일리지 및 청예조사료",
            selectionGroup: .tmr,
            category: .roughage,
            defaultPriceKrwPerKg: 180,
            nutrition: IngredientNutritionProfile(
                moisturePct: 71.03,
                dmPct: 28.97,
                cpPctDm: 9.38,
                tdnPctDm: 51.36,
                ndfPctDm: 63.03,
                adfPctDm: 40.21,
                nfcPctDm: 17.43,
                eePctDm: 2.77,
                ashPctDm: 7.37,
                caPctDm: 0.27,
                pPctDm: 0.19
            )
        ),
        IngredientDefinition(
            id: "FEED_85",
            sourceFeedNo: 85,
            name: "청예호밀(출수기)",
            sourceCategory: "사일리지 및 청예조사료",
            selectionGroup: .tmr,
            category: .roughage,
            defaultPriceKrwPerKg: 180,
            nutrition: IngredientNutritionProfile(
                moisturePct: 79.33,
                dmPct: 20.67,
                cpPctDm: 13.64,
                tdnPctDm: 60.94,
                ndfPctDm: 58.5,
                adfPctDm: 35.89,
                nfcPctDm: 9.84,
                eePctDm: 13.97,
                ashPctDm: 4.03,
                caPctDm: 0.14,
                pPctDm: 0.24
            )
        ),
        IngredientDefinition(
            id: "FEED_86",
            sourceFeedNo: 86,
            name: "총체벼사일리지(호숙기)",
            sourceCategory: "사일리지 및 청예조사료",
            selectionGroup: .tmr,
            category: .roughage,
            defaultPriceKrwPerKg: 180,
            nutrition: IngredientNutritionProfile(
                moisturePct: 60.0,
                dmPct: 40.0,
                cpPctDm: 9.25,
                tdnPctDm: 52.86,
                ndfPctDm: 56.27,
                adfPctDm: 41.16,
                nfcPctDm: 18.16,
                eePctDm: 3.13,
                ashPctDm: 13.16,
                caPctDm: 0.16,
                pPctDm: 0.18
            )
        ),
        IngredientDefinition(
            id: "FEED_87",
            sourceFeedNo: 87,
            name: "총체벼 사일리지(완숙기)",
            sourceCategory: "사일리지 및 청예조사료",
            selectionGroup: .tmr,
            category: .roughage,
            defaultPriceKrwPerKg: 180,
            nutrition: IngredientNutritionProfile(
                moisturePct: 60.66,
                dmPct: 39.34,
                cpPctDm: 6.99,
                tdnPctDm: 54.71,
                ndfPctDm: 57.44,
                adfPctDm: 42.47,
                nfcPctDm: 21.51,
                eePctDm: 2.24,
                ashPctDm: 11.79,
                caPctDm: 0.16,
                pPctDm: 0.18
            )
        ),
        IngredientDefinition(
            id: "FEED_88",
            sourceFeedNo: 88,
            name: "호밀사일리지(개화기)",
            sourceCategory: "사일리지 및 청예조사료",
            selectionGroup: .tmr,
            category: .roughage,
            defaultPriceKrwPerKg: 180,
            nutrition: IngredientNutritionProfile(
                moisturePct: 60.0,
                dmPct: 40.0,
                cpPctDm: 13.47,
                tdnPctDm: 59.3,
                ndfPctDm: 59.79,
                adfPctDm: 37.99,
                nfcPctDm: 16.59,
                eePctDm: 2.77,
                ashPctDm: 7.37,
                caPctDm: 0.27,
                pPctDm: 0.21
            )
        ),
        IngredientDefinition(
            id: "FEED_89",
            sourceFeedNo: 89,
            name: "호밀사일리지(출수기)",
            sourceCategory: "사일리지 및 청예조사료",
            selectionGroup: .tmr,
            category: .roughage,
            defaultPriceKrwPerKg: 180,
            nutrition: IngredientNutritionProfile(
                moisturePct: 60.0,
                dmPct: 40.0,
                cpPctDm: 14.18,
                tdnPctDm: 61.53,
                ndfPctDm: 53.92,
                adfPctDm: 35.12,
                nfcPctDm: 20.62,
                eePctDm: 4.03,
                ashPctDm: 7.23,
                caPctDm: 0.1,
                pPctDm: 0.24
            )
        ),
        IngredientDefinition(
            id: "FEED_90",
            sourceFeedNo: 90,
            name: "대두(콩)",
            sourceCategory: "견과종실류",
            selectionGroup: .tmr,
            category: .concentrate,
            defaultPriceKrwPerKg: 700,
            nutrition: IngredientNutritionProfile(
                moisturePct: 9.86,
                dmPct: 90.14,
                cpPctDm: 39.16,
                tdnPctDm: 100.81,
                ndfPctDm: 20.05,
                adfPctDm: 10.49,
                nfcPctDm: 15.56,
                eePctDm: 19.61,
                ashPctDm: 5.58,
                caPctDm: 0.22,
                pPctDm: 0.63
            )
        ),
        IngredientDefinition(
            id: "FEED_91",
            sourceFeedNo: 91,
            name: "루핀씨드",
            sourceCategory: "견과종실류",
            selectionGroup: .tmr,
            category: .concentrate,
            defaultPriceKrwPerKg: 700,
            nutrition: IngredientNutritionProfile(
                moisturePct: 10.53,
                dmPct: 89.47,
                cpPctDm: 34.1,
                tdnPctDm: 95.39,
                ndfPctDm: 27.84,
                adfPctDm: 18.29,
                nfcPctDm: 28.77,
                eePctDm: 6.21,
                ashPctDm: 3.06,
                caPctDm: 0.27,
                pPctDm: 0.34
            )
        ),
        IngredientDefinition(
            id: "FEED_92",
            sourceFeedNo: 92,
            name: "비트펄프",
            sourceCategory: "섬유질류_기타",
            selectionGroup: .tmr,
            category: .agriByproduct,
            defaultPriceKrwPerKg: 470,
            nutrition: IngredientNutritionProfile(
                moisturePct: 11.81,
                dmPct: 88.19,
                cpPctDm: 9.76,
                tdnPctDm: 76.66,
                ndfPctDm: 47.73,
                adfPctDm: 25.98,
                nfcPctDm: 36.82,
                eePctDm: 0.87,
                ashPctDm: 4.79,
                caPctDm: 1.11,
                pPctDm: 0.08
            )
        ),
        IngredientDefinition(
            id: "FEED_93",
            sourceFeedNo: 93,
            name: "옥공이",
            sourceCategory: "섬유질류_기타",
            selectionGroup: .tmr,
            category: .agriByproduct,
            defaultPriceKrwPerKg: 470,
            nutrition: IngredientNutritionProfile(
                moisturePct: 10.74,
                dmPct: 89.26,
                cpPctDm: 4.18,
                tdnPctDm: 58.3,
                ndfPctDm: 78.26,
                adfPctDm: 0.0,
                nfcPctDm: 14.07,
                eePctDm: 0.92,
                ashPctDm: 2.56,
                caPctDm: 0.06,
                pPctDm: 0.09
            )
        ),
        IngredientDefinition(
            id: "FEED_200",
            sourceFeedNo: 200,
            name: "엿밥",
            sourceCategory: "농식품부산물",
            selectionGroup: .tmr,
            category: .agriByproduct,
            defaultPriceKrwPerKg: 620,
            nutrition: IngredientNutritionProfile(
                moisturePct: 53.0,
                dmPct: 47.0,
                cpPctDm: 35.26,
                tdnPctDm: 88.0,
                ndfPctDm: 32.03,
                adfPctDm: 18.2,
                nfcPctDm: 20.48,
                eePctDm: 10.19,
                ashPctDm: 2.04,
                caPctDm: 0.09,
                pPctDm: 0.23
            )
        ),
        IngredientDefinition(
            id: "FEED_201",
            sourceFeedNo: 201,
            name: "아마박",
            sourceCategory: "농식품부산물",
            selectionGroup: .tmr,
            category: .concentrate,
            defaultPriceKrwPerKg: 620,
            nutrition: IngredientNutritionProfile(
                moisturePct: 11.34,
                dmPct: 88.66,
                cpPctDm: 39.92,
                tdnPctDm: 78.57,
                ndfPctDm: 42.01,
                adfPctDm: 21.77,
                nfcPctDm: 7.39,
                eePctDm: 3.97,
                ashPctDm: 6.71,
                caPctDm: 0.19,
                pPctDm: 0.7
            )
        ),
        IngredientDefinition(
            id: "FEED_202",
            sourceFeedNo: 202,
            name: "낙화생피",
            sourceCategory: "농식품부산물",
            selectionGroup: .tmr,
            category: .agriByproduct,
            defaultPriceKrwPerKg: 180,
            nutrition: IngredientNutritionProfile(
                moisturePct: 8.0,
                dmPct: 92.0,
                cpPctDm: 7.5,
                tdnPctDm: 42.39,
                ndfPctDm: 0.0,
                adfPctDm: 0.0,
                nfcPctDm: 0.0,
                eePctDm: 2.07,
                ashPctDm: 6.3,
                caPctDm: 0.2,
                pPctDm: 0.1
            )
        ),
        IngredientDefinition(
            id: "FEED_203",
            sourceFeedNo: 203,
            name: "야자박",
            sourceCategory: "농식품부산물",
            selectionGroup: .tmr,
            category: .agriByproduct,
            defaultPriceKrwPerKg: 410,
            nutrition: IngredientNutritionProfile(
                moisturePct: 10.39,
                dmPct: 89.61,
                cpPctDm: 23.54,
                tdnPctDm: 73.75,
                ndfPctDm: 0.0,
                adfPctDm: 0.0,
                nfcPctDm: 0.0,
                eePctDm: 5.51,
                ashPctDm: 6.93,
                caPctDm: 0.17,
                pPctDm: 0.71
            )
        ),
        IngredientDefinition(
            id: "FEED_204",
            sourceFeedNo: 204,
            name: "장유박",
            sourceCategory: "농식품부산물",
            selectionGroup: .tmr,
            category: .agriByproduct,
            defaultPriceKrwPerKg: 620,
            nutrition: IngredientNutritionProfile(
                moisturePct: 40.6,
                dmPct: 59.4,
                cpPctDm: 30.3,
                tdnPctDm: 66.06,
                ndfPctDm: 34.5,
                adfPctDm: 21.86,
                nfcPctDm: 9.94,
                eePctDm: 8.59,
                ashPctDm: 16.67,
                caPctDm: 0.0,
                pPctDm: 0.0
            )
        ),
        IngredientDefinition(
            id: "FEED_205",
            sourceFeedNo: 205,
            name: "맥아근",
            sourceCategory: "농식품부산물",
            selectionGroup: .tmr,
            category: .agriByproduct,
            defaultPriceKrwPerKg: 410,
            nutrition: IngredientNutritionProfile(
                moisturePct: 10.0,
                dmPct: 90.0,
                cpPctDm: 32.78,
                tdnPctDm: 61.0,
                ndfPctDm: 0.0,
                adfPctDm: 0.0,
                nfcPctDm: 0.0,
                eePctDm: 1.33,
                ashPctDm: 6.56,
                caPctDm: 0.27,
                pPctDm: 0.86
            )
        ),
        IngredientDefinition(
            id: "FEED_206",
            sourceFeedNo: 206,
            name: "맥강",
            sourceCategory: "농식품부산물",
            selectionGroup: .tmr,
            category: .agriByproduct,
            defaultPriceKrwPerKg: 410,
            nutrition: IngredientNutritionProfile(
                moisturePct: 10.8,
                dmPct: 89.2,
                cpPctDm: 12.03,
                tdnPctDm: 71.1,
                ndfPctDm: 0.0,
                adfPctDm: 0.0,
                nfcPctDm: 0.0,
                eePctDm: 6.3,
                ashPctDm: 8.48,
                caPctDm: 0.17,
                pPctDm: 0.56
            )
        ),
        IngredientDefinition(
            id: "FEED_207",
            sourceFeedNo: 207,
            name: "커피박",
            sourceCategory: "농식품부산물",
            selectionGroup: .tmr,
            category: .agriByproduct,
            defaultPriceKrwPerKg: 180,
            nutrition: IngredientNutritionProfile(
                moisturePct: 62.62,
                dmPct: 37.38,
                cpPctDm: 14.31,
                tdnPctDm: 60.01,
                ndfPctDm: 0.0,
                adfPctDm: 0.0,
                nfcPctDm: 0.0,
                eePctDm: 15.92,
                ashPctDm: 1.31,
                caPctDm: 0.13,
                pPctDm: 0.11
            )
        ),
        IngredientDefinition(
            id: "FEED_208",
            sourceFeedNo: 208,
            name: "채종박",
            sourceCategory: "농식품부산물",
            selectionGroup: .tmr,
            category: .concentrate,
            defaultPriceKrwPerKg: 620,
            nutrition: IngredientNutritionProfile(
                moisturePct: 11.45,
                dmPct: 88.55,
                cpPctDm: 40.17,
                tdnPctDm: 66.28,
                ndfPctDm: 0.0,
                adfPctDm: 0.0,
                nfcPctDm: 0.0,
                eePctDm: 3.37,
                ashPctDm: 9.36,
                caPctDm: 0.65,
                pPctDm: 1.19
            )
        ),
        IngredientDefinition(
            id: "FEED_209",
            sourceFeedNo: 209,
            name: "참깻묵(호마박)",
            sourceCategory: "농식품부산물",
            selectionGroup: .tmr,
            category: .concentrate,
            defaultPriceKrwPerKg: 620,
            nutrition: IngredientNutritionProfile(
                moisturePct: 11.03,
                dmPct: 88.97,
                cpPctDm: 51.46,
                tdnPctDm: 72.08,
                ndfPctDm: 0.0,
                adfPctDm: 0.0,
                nfcPctDm: 0.0,
                eePctDm: 4.78,
                ashPctDm: 13.49,
                caPctDm: 1.36,
                pPctDm: 1.1
            )
        ),
        IngredientDefinition(
            id: "FEED_210",
            sourceFeedNo: 210,
            name: "주정박",
            sourceCategory: "농식품부산물",
            selectionGroup: .tmr,
            category: .concentrate,
            defaultPriceKrwPerKg: 620,
            nutrition: IngredientNutritionProfile(
                moisturePct: 75.44,
                dmPct: 24.56,
                cpPctDm: 34.53,
                tdnPctDm: 77.61,
                ndfPctDm: 0.0,
                adfPctDm: 0.0,
                nfcPctDm: 0.0,
                eePctDm: 5.94,
                ashPctDm: 0.98,
                caPctDm: 0.0,
                pPctDm: 0.0
            )
        ),
        IngredientDefinition(
            id: "FEED_211",
            sourceFeedNo: 211,
            name: "옥수수",
            sourceCategory: "농식품부산물",
            selectionGroup: .tmr,
            category: .concentrate,
            defaultPriceKrwPerKg: 460,
            nutrition: IngredientNutritionProfile(
                moisturePct: 13.04,
                dmPct: 86.96,
                cpPctDm: 9.64,
                tdnPctDm: 88.22,
                ndfPctDm: 9.72,
                adfPctDm: 2.49,
                nfcPctDm: 74.83,
                eePctDm: 4.28,
                ashPctDm: 1.53,
                caPctDm: 0.02,
                pPctDm: 0.32
            )
        ),
        IngredientDefinition(
            id: "FEED_212",
            sourceFeedNo: 212,
            name: "소맥피(밀기울)",
            sourceCategory: "농식품부산물",
            selectionGroup: .tmr,
            category: .agriByproduct,
            defaultPriceKrwPerKg: 410,
            nutrition: IngredientNutritionProfile(
                moisturePct: 12.46,
                dmPct: 87.54,
                cpPctDm: 16.51,
                tdnPctDm: 74.72,
                ndfPctDm: 44.32,
                adfPctDm: 13.59,
                nfcPctDm: 29.35,
                eePctDm: 4.39,
                ashPctDm: 5.43,
                caPctDm: 0.13,
                pPctDm: 1.05
            )
        ),
        IngredientDefinition(
            id: "FEED_213",
            sourceFeedNo: 213,
            name: "사과박",
            sourceCategory: "농식품부산물",
            selectionGroup: .tmr,
            category: .agriByproduct,
            defaultPriceKrwPerKg: 180,
            nutrition: IngredientNutritionProfile(
                moisturePct: 84.91,
                dmPct: 15.09,
                cpPctDm: 5.77,
                tdnPctDm: 76.41,
                ndfPctDm: 0.0,
                adfPctDm: 0.0,
                nfcPctDm: 0.0,
                eePctDm: 7.02,
                ashPctDm: 3.58,
                caPctDm: 0.0,
                pPctDm: 0.0
            )
        ),
        IngredientDefinition(
            id: "FEED_214",
            sourceFeedNo: 214,
            name: "비트펄프",
            sourceCategory: "농식품부산물",
            selectionGroup: .tmr,
            category: .agriByproduct,
            defaultPriceKrwPerKg: 470,
            nutrition: IngredientNutritionProfile(
                moisturePct: 13.4,
                dmPct: 86.6,
                cpPctDm: 12.59,
                tdnPctDm: 74.57,
                ndfPctDm: 47.74,
                adfPctDm: 25.98,
                nfcPctDm: 32.75,
                eePctDm: 1.15,
                ashPctDm: 5.77,
                caPctDm: 0.68,
                pPctDm: 0.1
            )
        ),
        IngredientDefinition(
            id: "FEED_215",
            sourceFeedNo: 215,
            name: "비지",
            sourceCategory: "농식품부산물",
            selectionGroup: .tmr,
            category: .agriByproduct,
            defaultPriceKrwPerKg: 180,
            nutrition: IngredientNutritionProfile(
                moisturePct: 81.22,
                dmPct: 18.78,
                cpPctDm: 22.95,
                tdnPctDm: 81.36,
                ndfPctDm: 0.0,
                adfPctDm: 0.0,
                nfcPctDm: 0.0,
                eePctDm: 11.18,
                ashPctDm: 3.73,
                caPctDm: 0.21,
                pPctDm: 0.16
            )
        ),
        IngredientDefinition(
            id: "FEED_216",
            sourceFeedNo: 216,
            name: "미강",
            sourceCategory: "농식품부산물",
            selectionGroup: .tmr,
            category: .agriByproduct,
            defaultPriceKrwPerKg: 410,
            nutrition: IngredientNutritionProfile(
                moisturePct: 11.72,
                dmPct: 88.28,
                cpPctDm: 14.14,
                tdnPctDm: 87.97,
                ndfPctDm: 0.0,
                adfPctDm: 0.0,
                nfcPctDm: 0.0,
                eePctDm: 19.43,
                ashPctDm: 10.63,
                caPctDm: 0.02,
                pPctDm: 1.86
            )
        ),
        IngredientDefinition(
            id: "FEED_217",
            sourceFeedNo: 217,
            name: "면실박",
            sourceCategory: "농식품부산물",
            selectionGroup: .tmr,
            category: .concentrate,
            defaultPriceKrwPerKg: 620,
            nutrition: IngredientNutritionProfile(
                moisturePct: 11.28,
                dmPct: 88.72,
                cpPctDm: 35.46,
                tdnPctDm: 71.1,
                ndfPctDm: 51.26,
                adfPctDm: 32.27,
                nfcPctDm: 0.0,
                eePctDm: 34.83,
                ashPctDm: 7.5,
                caPctDm: 0.26,
                pPctDm: 1.03
            )
        ),
        IngredientDefinition(
            id: "FEED_218",
            sourceFeedNo: 218,
            name: "맥주박",
            sourceCategory: "농식품부산물",
            selectionGroup: .tmr,
            category: .concentrate,
            defaultPriceKrwPerKg: 620,
            nutrition: IngredientNutritionProfile(
                moisturePct: 72.1,
                dmPct: 27.9,
                cpPctDm: 29.03,
                tdnPctDm: 71.11,
                ndfPctDm: 57.93,
                adfPctDm: 27.06,
                nfcPctDm: 0.0,
                eePctDm: 6.81,
                ashPctDm: 6.45,
                caPctDm: 0.04,
                pPctDm: 0.22
            )
        ),
        IngredientDefinition(
            id: "FEED_219",
            sourceFeedNo: 219,
            name: "루핀",
            sourceCategory: "농식품부산물",
            selectionGroup: .tmr,
            category: .concentrate,
            defaultPriceKrwPerKg: 700,
            nutrition: IngredientNutritionProfile(
                moisturePct: 10.64,
                dmPct: 89.36,
                cpPctDm: 33.36,
                tdnPctDm: 94.85,
                ndfPctDm: 0.0,
                adfPctDm: 0.0,
                nfcPctDm: 0.0,
                eePctDm: 5.61,
                ashPctDm: 2.92,
                caPctDm: 0.24,
                pPctDm: 0.48
            )
        ),
        IngredientDefinition(
            id: "FEED_220",
            sourceFeedNo: 220,
            name: "들깻묵(임자박)",
            sourceCategory: "농식품부산물",
            selectionGroup: .tmr,
            category: .concentrate,
            defaultPriceKrwPerKg: 620,
            nutrition: IngredientNutritionProfile(
                moisturePct: 11.21,
                dmPct: 88.79,
                cpPctDm: 43.94,
                tdnPctDm: 1.63,
                ndfPctDm: 51.02,
                adfPctDm: 29.95,
                nfcPctDm: 0.0,
                eePctDm: 6.67,
                ashPctDm: 9.79,
                caPctDm: 0.56,
                pPctDm: 1.54
            )
        ),
        IngredientDefinition(
            id: "FEED_221",
            sourceFeedNo: 221,
            name: "대두피",
            sourceCategory: "농식품부산물",
            selectionGroup: .tmr,
            category: .agriByproduct,
            defaultPriceKrwPerKg: 410,
            nutrition: IngredientNutritionProfile(
                moisturePct: 11.03,
                dmPct: 88.97,
                cpPctDm: 13.18,
                tdnPctDm: 79.76,
                ndfPctDm: 59.91,
                adfPctDm: 42.99,
                nfcPctDm: 18.92,
                eePctDm: 2.29,
                ashPctDm: 5.7,
                caPctDm: 0.53,
                pPctDm: 0.39
            )
        ),
        IngredientDefinition(
            id: "FEED_222",
            sourceFeedNo: 222,
            name: "대두박",
            sourceCategory: "농식품부산물",
            selectionGroup: .tmr,
            category: .concentrate,
            defaultPriceKrwPerKg: 790,
            nutrition: IngredientNutritionProfile(
                moisturePct: 11.5,
                dmPct: 88.5,
                cpPctDm: 51.62,
                tdnPctDm: 83.06,
                ndfPctDm: 14.59,
                adfPctDm: 6.79,
                nfcPctDm: 24.54,
                eePctDm: 1.86,
                ashPctDm: 7.39,
                caPctDm: 0.43,
                pPctDm: 0.73
            )
        ),
        IngredientDefinition(
            id: "FEED_223",
            sourceFeedNo: 223,
            name: "감귤박",
            sourceCategory: "농식품부산물",
            selectionGroup: .tmr,
            category: .agriByproduct,
            defaultPriceKrwPerKg: 180,
            nutrition: IngredientNutritionProfile(
                moisturePct: 86.92,
                dmPct: 13.08,
                cpPctDm: 8.56,
                tdnPctDm: 82.87,
                ndfPctDm: 0.0,
                adfPctDm: 0.0,
                nfcPctDm: 0.0,
                eePctDm: 2.6,
                ashPctDm: 3.75,
                caPctDm: 0.0,
                pPctDm: 0.0
            )
        ),
        IngredientDefinition(
            id: "FEED_109",
            sourceFeedNo: 109,
            name: "석회석",
            sourceCategory: "광물질",
            selectionGroup: .mineral,
            category: .supplement,
            defaultPriceKrwPerKg: 120,
            nutrition: IngredientNutritionProfile(
                moisturePct: 0.05,
                dmPct: 99.95,
                cpPctDm: 0.0,
                tdnPctDm: 0.0,
                ndfPctDm: 0.0,
                adfPctDm: 0.0,
                nfcPctDm: 0.0,
                eePctDm: 0.0,
                ashPctDm: 98.99,
                caPctDm: 37.21,
                pPctDm: 0.01
            )
        ),
        IngredientDefinition(
            id: "FEED_110",
            sourceFeedNo: 110,
            name: "소금",
            sourceCategory: "광물질",
            selectionGroup: .mineral,
            category: .supplement,
            defaultPriceKrwPerKg: 120,
            nutrition: IngredientNutritionProfile(
                moisturePct: 0.0,
                dmPct: 100.0,
                cpPctDm: 0.0,
                tdnPctDm: 0.0,
                ndfPctDm: 0.0,
                adfPctDm: 0.0,
                nfcPctDm: 0.0,
                eePctDm: 0.0,
                ashPctDm: 99.7,
                caPctDm: 0.0,
                pPctDm: 0.0
            )
        ),
        IngredientDefinition(
            id: "FEED_111",
            sourceFeedNo: 111,
            name: "인산칼슘(제일)",
            sourceCategory: "광물질",
            selectionGroup: .mineral,
            category: .supplement,
            defaultPriceKrwPerKg: 120,
            nutrition: IngredientNutritionProfile(
                moisturePct: 2.54,
                dmPct: 97.46,
                cpPctDm: 0.0,
                tdnPctDm: 0.0,
                ndfPctDm: 0.0,
                adfPctDm: 0.0,
                nfcPctDm: 0.0,
                eePctDm: 0.0,
                ashPctDm: 0.0,
                caPctDm: 15.26,
                pPctDm: 24.22
            )
        ),
        IngredientDefinition(
            id: "FEED_112",
            sourceFeedNo: 112,
            name: "인산칼슘(제이)",
            sourceCategory: "광물질",
            selectionGroup: .mineral,
            category: .supplement,
            defaultPriceKrwPerKg: 120,
            nutrition: IngredientNutritionProfile(
                moisturePct: 3.58,
                dmPct: 96.42,
                cpPctDm: 0.0,
                tdnPctDm: 0.0,
                ndfPctDm: 0.0,
                adfPctDm: 0.0,
                nfcPctDm: 0.0,
                eePctDm: 0.0,
                ashPctDm: 0.0,
                caPctDm: 24.14,
                pPctDm: 19.63
            )
        ),
        IngredientDefinition(
            id: "FEED_113",
            sourceFeedNo: 113,
            name: "제삼인산칼슘",
            sourceCategory: "광물질",
            selectionGroup: .mineral,
            category: .supplement,
            defaultPriceKrwPerKg: 120,
            nutrition: IngredientNutritionProfile(
                moisturePct: 0.0,
                dmPct: 100.0,
                cpPctDm: 0.0,
                tdnPctDm: 0.0,
                ndfPctDm: 0.0,
                adfPctDm: 0.0,
                nfcPctDm: 0.0,
                eePctDm: 0.0,
                ashPctDm: 0.0,
                caPctDm: 35.02,
                pPctDm: 20.05
            )
        ),
        IngredientDefinition(
            id: "FEED_114",
            sourceFeedNo: 114,
            name: "인산칼슘(혼합)",
            sourceCategory: "광물질",
            selectionGroup: .mineral,
            category: .supplement,
            defaultPriceKrwPerKg: 120,
            nutrition: IngredientNutritionProfile(
                moisturePct: 2.27,
                dmPct: 97.73,
                cpPctDm: 0.0,
                tdnPctDm: 0.0,
                ndfPctDm: 0.0,
                adfPctDm: 0.0,
                nfcPctDm: 7.68,
                eePctDm: 0.0,
                ashPctDm: 0.0,
                caPctDm: 16.78,
                pPctDm: 23.09
            )
        ),
    ]
}
